### ISSUE TITLE
Support n:n relationships

### ISSUE THREAD

**Issue by gregmundy** [brighthive/data-resource-api#6]
Presently, the Data Resource APIs handles  1:1 and  1:n relationships. This enables the API to support queries such as `/endpoint` and `/endpoint/{id}`. In order to support deeper nesting of API queries, such as `/endpoint/{id}/other_endpoint`, the Data Resource API must be able to dynamically support n:n relationships that will be inferred from the schema.

**Comment by loganripplinger** [comment]
1. Sqlalchemy needs some code to recognize the relationshiphttps://docs.sqlalchemy.org/en/13/orm/basic_relationships.html#many-to-many
2. we also have to extend the flask portion to support m:n routes

**Comment by loganripplinger** [comment]
My current question is how are we going to extend the descriptor to support this.

There are three ways I can think of off the top of my head,
1. Separate junction table file
2. Put them in the foreign keys
3. Add a new section under foreign_keys

# Separate junction table file
This seems like the best approach. It actually models how the tables are setup more correctly and seems to make logical sense (for those with database experience) if you are trying to setup a junction table.

# Put in foreign keys
I don’t like this one because it can get really confusing and hard to figure out if you linked the right items in each separate file. Not sure how I feel about this one. This would require you to put the data in both files.

# Add a new section under foreign_keys
This seems logically better than putting in foreign keys section but still has similar drawbacks. You’d need to put it in both files.

Based on my current information I think the best option is to have a new separate junction table file.
